# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

navbar-links:
  Projects:
    - ABySS: "https://github.com/bcgsc/abyss#readme"
    - Brewsci/bio: "https://brewsci.github.io/homebrew-bio/"
    - Homebrew: "https://brew.sh"
    - Linuxbrew: "https://linuxbrew.sh"
    - ORCA: "http://www.bcgsc.ca/services/orca"
    - Tigmint: "https://bcgsc.github.io/tigmint/"
    - UniqTag: "https://github.com/sjackman/uniqtag#readme"
  Papers:
    - Google Scholar: "http://scholar.google.ca/citations?user=wFl3qXAAAAAJ"
    - PubMed: "https://www.ncbi.nlm.nih.gov/pubmed/?term=Jackman+Shaun%5BAuthor%5D"
    - ORCID: "https://orcid.org/0000-0002-9275-5966"
    - Impactstory: "https://impactstory.org/u/0000-0002-9275-5966"
    - Posters & Slides: "portfolio"
  Online:
    - GitHub: "https://github.com/sjackman"
    - Twitter: "http://twitter.com/sjackman"
    - LinkedIn: "http://www.linkedin.com/in/sjackman"
  Resume: "http://sjackman.ca/resume"
  About Me: "about-me"

twitter_username:
github_username:

# Build settings
markdown: kramdown
